import type { ContractStatus, PaymentStatus } from "@exactra/shared";

export const statusLabels: Record<ContractStatus, string> = {
  PENDING_PAYMENT: "Aguardando pagamento",
  ACTIVE: "Ativo",
  PAST_DUE: "Em atraso",
  CANCELED: "Cancelado",
  EXPIRED: "Vencido",
};

export const paymentStatusLabels: Record<PaymentStatus, string> = {
  PAID: "Pago",
  PENDING: "Pendente",
  FAILED: "Falhou",
};

export const adminCopy = {
  brand: "Painel Exactra",
  nav: [
    { href: "/admin", label: "Contratos" },
    { href: "/admin/leads", label: "Leads" },
    { href: "/admin/seguranca", label: "Segurança" },
  ],
  twoFactorBanner: {
    text: "Sua conta ainda não tem verificação em duas etapas.",
    cta: "Ativar agora",
  },
  signOut: "Sair",
  loading: "Carregando...",
  loadError: "Não foi possível carregar os dados. Recarregue a página.",
  pager: {
    label: "Paginação",
    prev: "Anterior",
    next: "Próxima",
    summary: (from: number, to: number, total: number) => `${from}–${to} de ${total}`,
  },
  login: {
    title: "Entrar no painel",
    email: "E-mail",
    password: "Senha",
    submit: "Entrar",
    forgot: "Esqueci minha senha",
    invalid: "E-mail ou senha incorretos.",
    mockHint: "Ambiente de teste: admin@exactra.com.br / exactra123. Código do app ou do e-mail: 123456.",
  },
  twoFactor: {
    title: "Verificação em duas etapas",
    text: "Digite o código de 6 dígitos do seu app autenticador.",
    code: "Código",
    backupText: "Use um dos códigos de recuperação que você salvou ao ativar a verificação.",
    backupCode: "Código de recuperação",
    otpText: (email: string) => `Enviamos um código de 6 dígitos para ${email || "o seu e-mail"}. Ele vale por poucos minutos.`,
    otpCode: "Código do e-mail",
    otpSendError: "Não foi possível enviar o código agora. Tente de novo.",
    resendOtp: "Reenviar código",
    useOtp: "Receber código por e-mail",
    useBackup: "Usar código de recuperação",
    useTotp: "Usar app autenticador",
    trustDevice: "Confiar neste dispositivo por 30 dias",
    submit: "Verificar",
    invalid: "Código inválido. Confira e tente de novo.",
  },
  forgot: {
    title: "Redefinir senha",
    text: "Informe seu e-mail. Se ele estiver cadastrado, você recebe um link para criar uma nova senha.",
    submit: "Enviar link",
    sent: "Se o e-mail estiver cadastrado, o link chega em alguns minutos. Confira também o spam.",
    back: "Voltar para o login",
  },
  reset: {
    title: "Criar nova senha",
    password: "Nova senha",
    confirm: "Repita a nova senha",
    hint: "Mínimo de 8 caracteres.",
    submit: "Salvar nova senha",
    tooShort: "A senha precisa ter pelo menos 8 caracteres.",
    mismatch: "As senhas não são iguais.",
    invalid: "Este link expirou ou já foi usado. Peça um novo.",
    done: "Senha alterada. Entre com a nova senha.",
    goLogin: "Ir para o login",
  },
  security: {
    title: "Verificação em duas etapas",
    intro: "Além da senha, o login pede um código do seu celular. Assim, ninguém entra no painel só com a sua senha.",
    password: "Sua senha",
    wrongPassword: "Senha incorreta.",
    enabled: "Ativada nesta conta.",
    disabled: "Desativada nesta conta.",
    start: "Ativar verificação",
    scanTitle: "1. Escaneie o QR code",
    scanText: "Abra um app autenticador (Google Authenticator, Microsoft Authenticator ou similar) e escaneie o código.",
    manualLabel: "Sem câmera? Digite esta chave no app:",
    backupTitle: "2. Guarde os códigos de recuperação",
    backupText: "Cada código entra uma única vez, se você perder o celular. Guarde num lugar seguro, fora deste computador.",
    copyCodes: "Copiar códigos",
    copied: "Copiados",
    verifyTitle: "3. Confirme com o código do app",
    code: "Código de 6 dígitos",
    confirm: "Confirmar e ativar",
    invalidCode: "Código inválido. Confira o horário do celular e tente de novo.",
    done: "Pronto. A partir do próximo login, o painel vai pedir o código do app.",
    regenerateTitle: "Novos códigos de recuperação",
    regenerateText: "Gera uma nova lista e invalida os códigos antigos.",
    regenerate: "Gerar novos códigos",
    disableTitle: "Desativar a verificação",
    disableText: "Não recomendado: o login volta a pedir só a senha.",
    disable: "Desativar",
    cancel: "Cancelar",
  },
  metrics: {
    activeCustomers: "Clientes ativos",
    newThisMonth: "Novos nos últimos 30 dias",
    contractedRevenueCents: "Receita contratada",
    pendingPayment: "Aguardando pagamento",
    expiringIn30Days: "Vencem em 30 dias",
    byPlan: "Ativos por plano",
    byMethod: "Ativos por forma de pagamento",
  },
  contracts: {
    title: "Contratos",
    search: "Buscar por nome, e-mail ou documento",
    allStatuses: "Todos os status",
    allPlans: "Todos os planos",
    allMethods: "Todas as formas",
    exportCsv: "Exportar CSV",
    csvName: "contratos-exactra.csv",
    empty: "Nenhum contrato encontrado com esses filtros.",
    exportError: "Não foi possível exportar agora. Tente de novo.",
    cols: { customer: "Cliente", plan: "Plano", method: "Pagamento", status: "Status", startsAt: "Início", endsAt: "Vence em" },
  },
  detail: {
    back: "Voltar para contratos",
    notFound: "Contrato não encontrado.",
    customer: "Cliente",
    email: "E-mail",
    phone: "Telefone",
    document: "CPF/CNPJ",
    contract: "Contrato",
    plan: "Plano",
    period: "Período",
    method: "Forma de pagamento",
    amount: "Valor por cobrança",
    createdAt: "Criado em",
    startsAt: "Início",
    endsAt: "Vence em",
    payments: "Histórico de pagamentos",
    noPayments: "Nenhum pagamento registrado.",
    lead: "Veio do simulador",
    leadSummary: (revenue: string, plan: string, date: string) => `Faturamento informado ${revenue}, plano sugerido ${plan}, em ${date}`,
    cols: { date: "Data", amount: "Valor", method: "Forma", status: "Status" },
  },
  leads: {
    title: "Leads do simulador",
    search: "Buscar por nome, e-mail ou WhatsApp",
    empty: "Nenhum lead ainda. Eles aparecem aqui quando alguém libera o resultado do simulador.",
    cols: { name: "Nome", whatsapp: "WhatsApp", revenue: "Faturamento", plan: "Plano sugerido", source: "Origem", createdAt: "Data" },
    noSource: "Direto",
  },
};
