import type { ContractStatus } from "@exactra/shared";
import type { AdminPayment } from "@/lib/api/admin-types";

export const statusLabels: Record<ContractStatus, string> = {
  PENDING_PAYMENT: "Aguardando pagamento",
  ACTIVE: "Ativo",
  PAST_DUE: "Em atraso",
  CANCELED: "Cancelado",
  EXPIRED: "Vencido",
};

export const paymentStatusLabels: Record<AdminPayment["status"], string> = {
  PAID: "Pago",
  PENDING: "Pendente",
  FAILED: "Falhou",
  REFUNDED: "Estornado",
};

export const adminCopy = {
  brand: "Painel Exactra",
  nav: [
    { href: "/admin", label: "Contratos" },
    { href: "/admin/leads", label: "Leads" },
  ],
  signOut: "Sair",
  loading: "Carregando...",
  loadError: "Não foi possível carregar os dados. Recarregue a página.",
  login: {
    title: "Entrar no painel",
    email: "E-mail",
    password: "Senha",
    submit: "Entrar",
    forgot: "Esqueci minha senha",
    invalid: "E-mail ou senha incorretos.",
    mockHint: "Ambiente de teste: admin@exactra.com.br / exactra123, código 123456.",
  },
  twoFactor: {
    title: "Verificação em duas etapas",
    text: "Digite o código de 6 dígitos do seu app autenticador.",
    code: "Código",
    backupText: "Use um dos códigos de recuperação que você salvou ao ativar a verificação.",
    backupCode: "Código de recuperação",
    useBackup: "Usar código de recuperação",
    useTotp: "Usar app autenticador",
    trustDevice: "Confiar neste dispositivo por 30 dias",
    submit: "Verificar",
    invalid: "Código inválido. Confira e tente de novo.",
  },
  forgot: {
    title: "Redefinir senha",
    text: "Informe seu e-mail. Se ele estiver cadastrado, você recebe um link para criar uma nova senha.",
    submit: "Enviar link",
    sent: "Se o e-mail estiver cadastrado, o link chega em alguns minutos. Confira também o spam.",
    back: "Voltar para o login",
  },
  reset: {
    title: "Criar nova senha",
    password: "Nova senha",
    confirm: "Repita a nova senha",
    hint: "Mínimo de 8 caracteres.",
    submit: "Salvar nova senha",
    tooShort: "A senha precisa ter pelo menos 8 caracteres.",
    mismatch: "As senhas não são iguais.",
    invalid: "Este link expirou ou já foi usado. Peça um novo.",
    done: "Senha alterada. Entre com a nova senha.",
    goLogin: "Ir para o login",
  },
  metrics: {
    activeCustomers: "Clientes ativos",
    newThisMonth: "Novos nos últimos 30 dias",
    contractedRevenueCents: "Receita contratada",
    pendingPayment: "Aguardando pagamento",
    expiringIn30Days: "Vencem em 30 dias",
    byPlan: "Ativos por plano",
    byMethod: "Ativos por forma de pagamento",
  },
  contracts: {
    title: "Contratos",
    search: "Buscar por nome, e-mail ou documento",
    allStatuses: "Todos os status",
    allPlans: "Todos os planos",
    allMethods: "Todas as formas",
    exportCsv: "Exportar CSV",
    csvName: "contratos-exactra.csv",
    empty: "Nenhum contrato encontrado com esses filtros.",
    cols: { customer: "Cliente", plan: "Plano", method: "Pagamento", status: "Status", startsAt: "Início", endsAt: "Vence em" },
  },
  detail: {
    back: "Voltar para contratos",
    notFound: "Contrato não encontrado.",
    customer: "Cliente",
    email: "E-mail",
    phone: "Telefone",
    document: "CPF/CNPJ",
    contract: "Contrato",
    plan: "Plano",
    period: "Período",
    method: "Forma de pagamento",
    amount: "Valor por cobrança",
    createdAt: "Criado em",
    startsAt: "Início",
    endsAt: "Vence em",
    payments: "Histórico de pagamentos",
    noPayments: "Nenhum pagamento registrado.",
    cols: { date: "Data", amount: "Valor", method: "Forma", status: "Status" },
  },
  leads: {
    title: "Leads do simulador",
    empty: "Nenhum lead ainda. Eles aparecem aqui quando alguém libera o resultado do simulador.",
    cols: { name: "Nome", whatsapp: "WhatsApp", revenue: "Faturamento", plan: "Plano sugerido", source: "Origem", createdAt: "Data" },
    noSource: "Direto",
  },
};
